### ISSUE TITLE
metrics issue with exporter in Cassandra 4.0

### ISSUE THREAD

**Issue by ducnm0711** [criteo/cassandra_exporter#102]
Hi 
We've been using criteo `cassandra_exporter` with Cassandra 3.11.5 for a year. I notice some error with metrics after update to 4.0 and OpenJDK 11. 

Currently my workaround is to blacklisted all error metrics. Below here is the list of metrics that throwing error:
JDK8:
```
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for org:apache:cassandra:net:messagingservice:backpressureperhost BackPressurePerHost
javax.management.RuntimeMBeanException: java.lang.UnsupportedOperationException: This feature has been removed
```
JDK 11:
```
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=metaspace:memorypool:collectionusagethreshold CollectionUsageThreshold
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=metaspace:memorypool:collectionusagethresholdexceeded CollectionUsageThresholdExceeded
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=metaspace:memorypool:collectionusagethresholdcount CollectionUsageThresholdCount
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:runtime:bootclasspath BootClassPath
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'profiled_nmethods':memorypool:collectionusagethreshold CollectionUsageThreshold
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'profiled_nmethods':memorypool:collectionusagethresholdexceeded CollectionUsageThresholdExceeded
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'profiled_nmethods':memorypool:collectionusagethresholdcount CollectionUsageThresholdCount
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'non-nmethods':memorypool:collectionusagethreshold CollectionUsageThreshold
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'non-nmethods':memorypool:collectionusagethresholdexceeded CollectionUsageThresholdExceeded
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'non-nmethods':memorypool:collectionusagethresholdcount CollectionUsageThresholdCount
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'non-profiled_nmethods':memorypool:collectionusagethreshold CollectionUsageThreshold
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'non-profiled_nmethods':memorypool:collectionusagethresholdexceeded CollectionUsageThresholdExceeded
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=codeheap_'non-profiled_nmethods':memorypool:collectionusagethresholdcount CollectionUsageThresholdCount
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=g1_survivor_space:memorypool:usagethreshold UsageThreshold
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=g1_survivor_space:memorypool:usagethresholdexceeded UsageThresholdExceeded
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=g1_survivor_space:memorypool:usagethresholdcount UsageThresholdCount
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=compressed_class_space:memorypool:collectionusagethreshold CollectionUsageThreshold
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=compressed_class_space:memorypool:collectionusagethresholdexceeded CollectionUsageThresholdExceeded
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=compressed_class_space:memorypool:collectionusagethresholdcount CollectionUsageThresholdCount
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for org:apache:cassandra:net:messagingservice:backpressureperhost BackPressurePerHost
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=g1_eden_space:memorypool:usagethreshold UsageThreshold
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=g1_eden_space:memorypool:usagethresholdexceeded UsageThresholdExceeded
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for java:lang:name=g1_eden_space:memorypool:usagethresholdcount UsageThresholdCount
```

**Comment by chibenwa** [comment]
Here are the blacklist we needed to set up:

```
   # Unaccessible metrics Java 11 (not enough privilege)
   - java:lang:runtime:bootclasspath
   - org:apache:cassandra:net:messagingservice:backpressureperhost   
   - .*:memorypool:collectionusagethreshold
   - .*:memorypool:collectionusagethresholdexceeded
   - .*:memorypool:collectionusagethresholdcount
   - .*:memorypool:usagethreshold
   - .*:memorypool:usagethresholdcount
   - .*:memorypool:usagethresholdexceeded
```

**Comment by carrodher** [comment]
Hi, this also happens to me:
```
[main] INFO com.criteo.nosql.cassandra.exporter.Config - Loading yaml config from ./config.yml
[main] ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for org:apache:cassandra:net:messagingservice:backpressureperhost BackPressurePerHost
javax.management.RuntimeMBeanException: java.lang.UnsupportedOperationException: This feature has been removed
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:839)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:651)
```

Is there any way to work around this?
