### ISSUE TITLE
Exporter stops with "CollectionUsage threshold is not supported"

### ISSUE THREAD

**Issue by catalinmer** [criteo/cassandra_exporter#116]
Hi,
I have the exporter running on java8 and cassandra 3.11, however after upgrading to java11 and cassandra 4.1 doesn't seem to work anymore. The following exceptions are present:

`ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for com.criteo.nosql.cassandra.exporter.JmxScraper$MBeanInfo@51b55cb0CollectionUsageThresholdCount
anagement.RuntimeMBeanException: java.lang.UnsupportedOperationException: CollectionUsage threshold is not supported
 at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:829)
 at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:842)
 at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:645)
 at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
 at java.base/jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
`
.
.
then 
`prometheus_cassandra_exporter[24892]: [main] ERROR com.criteo.nosql.cassandra.exporter.Main - Scrapper stopped due to uncaught exception
 prometheus_cassandra_exporter[24892]: java.lang.ClassCastException`

any help will will be appreciated, thank you

**Comment by catalinmer** [comment]
Looks like upgrading to latest version (2.3.8) works just fine.
