### ISSUE TITLE
Cannot retrieve the datacenter name information for the node

### ISSUE THREAD

**Issue by ChaitanyaManthena** [criteo/cassandra_exporter#76]
Hi Team,

When i run the command to start the exporter(2.3.4) getting the below error. 

[main] INFO com.criteo.nosql.cassandra.exporter.Config - Loading yaml config from config.yml
[main] TRACE com.criteo.nosql.cassandra.exporter.Config - com.criteo.nosql.cassandra.exporter.Config@887af79
[main] ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot retrieve the datacenter name information for the node
javax.management.AttributeNotFoundException: No such attribute: HostIdToEndpoint
        at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:81)
        at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
        at com.criteo.nosql.cassandra.exporter.JmxScraper$NodeInfo.getNodeInfo(JmxScraper.java:413)
        at com.criteo.nosql.cassandra.exporter.JmxScraper.run(JmxScraper.java:175)
        at com.criteo.nosql.cassandra.exporter.Main.start(Main.java:38)
        at com.criteo.nosql.cassandra.exporter.Main.main(Main.java:30)

**Comment by yakirgb** [comment]
What is your cassandra version?

**Comment by ChaitanyaManthena** [comment]
Hi @yakirgb 

Thank you for your quick response, we are using apache-cassandra-2.1.9.

**Comment by yakirgb** [comment]
You need to have at least Cassandra 2.2.x in order to use the exporter.

**Comment by ChaitanyaManthena** [comment]
@yakirgb 

Thank you so much for the quick update and will work to get cassandra upgraded.

**Comment by ChaitanyaManthena** [comment]
@yakirgb 

Just want to check is there a lower version of exporter supports apache-cassandra-2.1.9.

**Comment by erebe** [comment]
Yep, the https://github.com/criteo/cassandra_exporter/releases/tag/1.0.1 version works with cassandra 2.1.x, i don't think there is any bug but you will lack some information.

Maybe it will be good enough for you

**Comment by ChaitanyaManthena** [comment]
@yakirgb 
Thank you for the information will try that.

**Comment by ChaitanyaManthena** [comment]
@yakirgb 
thank you so much for your help the mentioned jar is working and able to generate the metrics. 

I wanted to check is there a possibility to run the exporter jar from any other remote machine (non cassandra) to collect the metrics of cassandra server.

**Comment by erebe** [comment]
yes, 
in the config file, first line, there is a host config. Put the ip/hostname of the node you want to scrap remotly. It will work but aware that it will be slow.

Don't forget that you need to scrap every cassandra node in order to to get a complete view of the cluster and that the exporter can only scrap one node

**Comment by ChaitanyaManthena** [comment]
@erebe 

Thank you so much for your information, can i run multiple cassandra instances in the remote server to get the metrics.

**Comment by nishimwe13** [comment]
@erebe do you have any idea of how to solve the issue posted above by @rafi ?
I am facing the same issue with cassandra 3.11.4 and exporter 2.3.4 
Thanks.

**Comment by erebe** [comment]
Hello @nishimwe13 ,

Sadly no, and I don't work anymore for Criteo (the company owning the repository) so I don't have any rights on it anymore.
