### ISSUE TITLE
Error: Unrecognized field "maxScrapeFrequencyInSec"

### ISSUE THREAD

**Issue by rjshrjndrn** [criteo/cassandra_exporter#86]
Hi,
 I was trying to use this exporter, but getting this error.
Steps to reproduce.
1. Vanilla cassandra single node installation
2. download 2.3.5 jar from release and config from read me file
3. java -jar cassandra_exporter-2.3.5.jar config.yml
```
root@cassandra-0:~# java -jar cassandra_exporter-2.3.5.jar config.yml
[main] INFO com.criteo.nosql.cassandra.exporter.Config - Loading yaml config from config.yml
[main] ERROR com.criteo.nosql.cassandra.exporter.Config - Cannot load config file
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "maxScrapeFrequencyInSec" (class com.criteo.nosql.cassandra.exporter.Config), not marked as ignorable (9 known properties: "host", "additionalLabelsFromEnvvars", "user", "ssl", "blacklist", "listenPort", "password", "listenAddress", "maxScrapFrequencyInSec"])
 at [Source: (File); line: 60, column: 3] (through reference chain: com.criteo.nosql.cassandra.exporter.Config["maxScrapeFrequencyInSec"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
        at com.criteo.nosql.cassandra.exporter.Config.fromFile(Config.java:34)
        at com.criteo.nosql.cassandra.exporter.Main.main(Main.java:21)
[main] ERROR com.criteo.nosql.cassandra.exporter.Main - Cannot parse config file present at config.yml
```

**Comment by erebe** [comment]
Should be better with https://github.com/criteo/cassandra_exporter/commit/c608d95b263d900669ab0f0538f7b37526ce10a7

**Comment by rjshrjndrn** [comment]
Raised a PR #87
